### ISSUE TITLE
The FFI implementation of sqflite_tizen

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/plugins#277]
### Source code

https://github.com/swift-kim/plugins/tree/sqflite/packages/sqflite

### Usage

Add `sqflite_tizen` as a git package dependency in your pubspec.yaml.
```yaml
dependencies:
  sqflite:
  sqflite_tizen:
    git: https://github.com/swift-kim/plugins
    ref: sqflite
    path: packages/sqflite
```

### Current status

The following tests (from the sqflite example app) are currently failing. No critical error found. None of the errors are Tizen-specific.

- Raw tests
  - **Options**: Not implemented by sqflite_common_ffi.
  - **Debug mode (log)**: Partially implemented by sqflite_common_ffi.
  - **without rowid**: Bad test case (0 is returned on Tizen).
- Open tests
  - **open in transaction**: A bug in sqflite_common_ffi.
  - **Open non sqlite file**: Bad test case (succeeds only on Android).
- Type tests
  - **blob**: Not implemented by sqflite_common_ffi (see `getSqlArguments` in `sqflite_ffi_impl.dart`).
  - **bool**: Not implemented by sqflite_common_ffi.
- Exp tests
  - **sql dump file**
- Exception tests
  - **Sqlite Exception**
  - **Sqlite batch Exception**
  - **Bind no argument (no iOS)**
  - **crash ios (no iOS)**
  - **Bind no parameter**
  - **Thread dead lock**

https://github.com/flutter-tizen/plugins/pull/276#issuecomment-970168882
