### ISSUE TITLE
Unresolved reference: samsung kotlin(UNRESOLVED_REFERENCE)

### ISSUE THREAD

**Issue by ZanzyTHEbar** [flutter-tizen/plugins#669]
i have a working flutter project for WearOS and i would like to add the `wear_rotary` package, however after adding the flutter dependancy: 
```yml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  wear: ^1.1.0
  wearable_rotary: ^2.0.2
  square_percent_indicater: ^0.1.0
```
I can not import `com.samsung.wear_rotary` into my `MainActivity.kt`.

```kt
package com.example.watch_app

import android.view.MotionEvent
import com.samsung.wearable_rotary.WearableRotaryPlugin // error is here
import io.flutter.embedding.android.FlutterActivity

class MainActivity : FlutterActivity() {
    override fun onGenericMotionEvent(event: MotionEvent): Boolean {
        return when {
            WearableRotaryPlugin.onGenericMotionEvent(event) -> true
            else -> super.onGenericMotionEvent(event)
        }
    }
}
```
