### ISSUE TITLE
Smart Tv Samsung Player

### ISSUE THREAD

**Issue by isnzenauz** [flutter-tizen/plugins#777]
Hey Flutter-Tizen Team,
Thanks for this a lot of support its a good job, thanks again.

Im build app of media player to display content of m3u8, not included channels its pure media player.
so i need to publish it to samsung store, the app already working stabel in android phones and android tv, web too.

In liste below my dependencies, i need to know if will work good in samsung tvs,
and what is good for me to display video lives and vods with good rendring no lags its vido_player_tizen or video_player_videohole, video_player_avplay

if its video_player_videohole or avplay can you please tell me how i will integrate it, and with videohole - avplay can i use just TV Emulator to test the player without Real Device

Thank you so mush <3.
Best regards

name: SAID Media TV PLAYER
description: A SUPER TV MEDIA PLAYER.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_animate: ^4.5.0
  youtube_player_flutter: ^9.0.3
  flutter_native_splash: ^2.4.1
  device_uuid: ^0.0.4
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  heroicons_flutter: ^0.4.0
  wakelock_plus: ^1.2.8
  connectivity_plus: ^5.0.1
  url_launcher: ^6.3.0
  dio: ^5.6.0
  email_otp: ^2.1.2
  font_awesome_flutter: ^10.7.0
  video_player: ^2.9.2
  fvp: ^0.27.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  cached_network_image: ^3.4.1
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  dpad_container: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  android: true
  color: "#352A6E"
  image: assets/images/splash_logo.png
  fullscreen: true
  android_12:
    image: assets/images/splash_logo.png
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/animated/

**Comment by JSUYA** [comment]
Hi, thank you for your interesting.

You may need to add *_tizen packages. like this..
```yaml
  http: ^1.2.2
  flutter_animate: ^4.5.0
  youtube_player_flutter: ^9.0.3
  flutter_native_splash: ^2.4.1
  device_uuid: ^0.0.4
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  google_fonts: ^6.2.1
  heroicons_flutter: ^0.4.0
  wakelock_plus: ^1.2.8
  # connectivity_plus: ^5.0.1
  connectivity_plus: ^6.1.0
  connectivity_plus_tizen: ^1.2.0
  # url_launcher: ^6.3.0
  url_launcher: ^6.1.0
  url_launcher_tizen: ^2.1.2
  dio: ^5.6.0
  email_otp: ^2.1.2
  font_awesome_flutter: ^10.7.0
  # video_player: ^2.9.2
  video_player_avplay: ^0.5.5
  fvp: ^0.27.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  cached_network_image: ^3.4.1
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  dpad_container: ^2.0.4

  # In use in above packages
  package_info_plus_tizen: ^1.0.4
  sqflite_tizen: ^0.1.3
```
But there seem to be some problems.
- It depends on which video API you used, and there is no guide. APIs like DurationRage may have different usability, and there may be unimplemented APIs.
  +) If you have any API requirements or requests, we can review them.
- It seems to use youtube_player_flutter, but this is not supported.
- Since avplay is a player that supports DRM, it has hardware dependency. Therefore, it cannot be used on the emulator.

Thanks
